### ISSUE TITLE
( ͡° ͜ʖ ͡° )

### ISSUE THREAD

**Issue by Litzlfellner** [if-03-01-C-fall-2017/reading-assignment-1-Amel-Dzogovic#1]
Meh

**Comment by Amel-Dzogovic** [comment]
lappen

**Comment by Litzlfellner** [comment]
Meh

**Comment by Amel-Dzogovic** [comment]
Lappen

**Comment by Litzlfellner** [comment]
Meh

**Comment by Amel-Dzogovic** [comment]
![katzenschaf2](https://user-images.githubusercontent.com/32106462/30632653-2aa00a42-9de9-11e7-9c6f-1601f799354f.jpg)

**Comment by Litzlfellner** [comment]
![f3e515c9e6293dc5adfe66aa68558116--a-meme-sheep](https://user-images.githubusercontent.com/32123817/30632765-915375a8-9de9-11e7-9de2-1909dee05992.jpg)

**Comment by Amel-Dzogovic** [comment]
![a-warlock-in-destiny-2-using-the-new-dawnbreak-super-which-gives-you-access-to-powerful-solar-swo](https://user-images.githubusercontent.com/32106462/30632935-1adb1bc8-9dea-11e7-97fb-876e9053f892.png)

**Comment by Litzlfellner** [comment]
![cqmtfed](https://user-images.githubusercontent.com/32123817/30632985-50040f4e-9dea-11e7-8414-3f2f8c2e21c2.jpg)

**Comment by Amel-Dzogovic** [comment]
patrick keine apfel in der klasse essen man darf das nicht

**Comment by Litzlfellner** [comment]
Mach ich gar nicht :(
